---
- name: VPS deployment
  hosts: vps
  become: true
  tags:
    - vps
  vars:
    docker_network_name: vps
  roles:
    - role: vps_baseline
      tags:
        - vps_baseline
    - role: ntopng
      tags:
        - ntopng
    - role: headscale
      tags:
        - headscale
